title: "Ankit Gupta"
email: ankitgupta_ug@ee.nits.ac.in
description: >- # this means to ignore newlines until "baseurl:"
 Ankit Gupta, Part time Full Stack Developer with skills of Angular, ML/AI, Python Automation and TensorFlow. 
 Full time student at NIT Silchar in Electrical Engineering.
baseurl: "/" 
url: "https://luckyhero613.github.io/" 
twitter_username: luckyhero613
github_username:  luckyhero613

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
